version: '3'

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./create_table_people.sql:/docker-entrypoint-initdb.d/create_table_people.sql
    environment:
      - MYSQL_DATABASE=appdb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD
    ports:
      - "3300:3306" # a maquina root ja possui mysql
    networks:
      - minha-rede

  app:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    image: brunoccintra/app:prod  
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 50s node index.js
    tty: true
    volumes:
      - ./app:/usr/src/app
    networks:
      - minha-rede
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: brunoccintra/nginx:prod
    container_name: nginx
    ports:
      - "8080:8080"
    tty: true
    networks:
      - minha-rede
    depends_on:
      - app

networks:
  minha-rede:
    driver: bridge